# Generated by Django 4.2.16 on 2026-08-19 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, unique=True)),
                ('numero_pedido', models.CharField(blank=True, db_column='numeroPedido', max_length=50)),
                ('tipo', models.CharField(choices=[('Empréstimo', 'Empréstimo'), ('Cessão', 'Cessão'), ('Reserva', 'Reserva')], default='Empréstimo', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Aguardando aprovação'), ('aprovado', 'Aprovado / Liberado'), ('aguardando_devolucao', 'Aguard. confirmação devolução'), ('devolvido', 'Devolvido'), ('cancelado', 'Cancelado'), ('recusado', 'Recusado')], default='pendente', max_length=25)),
                ('produto', models.CharField(max_length=255)),
                ('produto_concedente', models.CharField(blank=True, max_length=255)),
                ('mg_solicitante', models.CharField(blank=True, choices=[('', '—'), ('MG1', 'MG1'), ('MG2', 'MG2'), ('MG3', 'MG3'), ('MG4', 'MG4'), ('Cenografia', 'Cenografia'), ('Arte', 'Arte')], max_length=20)),
                ('mg_concedente', models.CharField(blank=True, choices=[('', '—'), ('MG1', 'MG1'), ('MG2', 'MG2'), ('MG3', 'MG3'), ('MG4', 'MG4'), ('Cenografia', 'Cenografia'), ('Arte', 'Arte')], max_length=20)),
                ('localizacao', models.CharField(blank=True, max_length=255)),
                ('solicitante_nome', models.CharField(blank=True, max_length=200)),
                ('solicitante_email', models.CharField(blank=True, max_length=200)),
                ('concedente_nome', models.CharField(blank=True, max_length=200)),
                ('concedente_email', models.CharField(blank=True, max_length=200)),
                ('inicio_iso', models.DateField(blank=True, null=True)),
                ('dev_iso', models.DateField(blank=True, null=True)),
                ('devolvido_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('materiais', models.JSONField(blank=True, default=list)),
                ('fotos', models.JSONField(blank=True, default=list)),
                ('pdfs', models.JSONField(blank=True, default=list)),
                ('ocorrencia', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('firebase_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('concedente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_concedidos', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_criados', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
