# Generated by Django 4.2.16 on 2026-08-27 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='localizacao_tipo',
            field=models.CharField(blank=True, choices=[('armazenagem', 'Armazenagem'), ('externa', 'Externa'), ('cc', 'CC'), ('estudio', 'Estúdio')], max_length=20),
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('mg', models.CharField(choices=[('', '—'), ('MG1', 'MG1'), ('MG2', 'MG2'), ('MG3', 'MG3'), ('MG4', 'MG4'), ('Cenografia', 'Cenografia'), ('Arte', 'Arte')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estúdio',
                'verbose_name_plural': 'Estúdios',
                'ordering': ['mg', 'nome'],
                'unique_together': {('nome', 'mg')},
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='pedidos.estudio'),
        ),
    ]
