# Generated by Django 4.2.16 on 2026-08-19 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(blank=True, max_length=100)),
                ('matricula', models.CharField(blank=True, max_length=50)),
                ('setor', models.CharField(blank=True, choices=[('MG1', 'MG1'), ('MG2', 'MG2'), ('MG3', 'MG3'), ('MG4', 'MG4'), ('Cenografia', 'Cenografia'), ('Arte', 'Arte')], max_length=20)),
                ('cargo', models.CharField(blank=True, choices=[('Aux. Almoxarifado', 'Aux. Almoxarifado'), ('Almoxarife', 'Almoxarife'), ('Encarregado', 'Encarregado'), ('Supervisor', 'Supervisor'), ('Coordenador', 'Coordenador'), ('Gerente', 'Gerente'), ('Gerente Geral', 'Gerente Geral')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('perms', models.JSONField(blank=True, default=dict)),
                ('firebase_uid', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('matricula', models.CharField(blank=True, max_length=50)),
                ('senha_hash', models.CharField(max_length=128)),
                ('setor', models.CharField(blank=True, max_length=20)),
                ('cargo', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('avaliado_em', models.DateTimeField(blank=True, null=True)),
                ('avaliado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_avaliadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de acesso',
                'verbose_name_plural': 'Solicitações de acesso',
                'ordering': ['-criado_em'],
            },
        ),
    ]
