# Generated by Django 4.2.16 on 2026-08-19 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pedido_novo', 'Novo pedido'), ('pedido_aprovado', 'Pedido aprovado'), ('pedido_recusado', 'Pedido recusado'), ('pedido_devolvido', 'Pedido devolvido'), ('atraso', 'Prazo em atraso'), ('sistema', 'Sistema')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField(blank=True)),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pedido_id', models.IntegerField(blank=True, null=True)),
                ('firebase_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
